# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4ee5b03a631d22fadd2ec299461145f728670b0a5ad56e703a62f9a1184c2c32cc8b0e318b772c6e78523728aebb99a663d2a5490809e5eab281b3cfd8b3ff42

test:
  secret_key_base: a418d929f9870abdb96f4dad1397f60226ec1911ac5ec629d190320774b95650137c43af8dbe2cd060eda39deee4458878a8c28cf5a93bf95eff1eb3ef5f8f82

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
